### PR TITLE
Fixed calculation of sun position

### PR DESCRIPTION
**Pull request by mostaphaRoudsari**
Hi @theo-armour,

I know that you [asked me to wait](https://github.com/ladybug-analysis-tools/ladybug-web/issues/2) but after reading your comment about sunCalc I couldn't stop myself from taking a closer look.

I made a couple of modifications to your code and now the results looks as expected:

image

First change is in creating date. Since we want the date to be create for the location I created the UTC date first and then adjusted the time based on time zone. For  now [I set the timezone to a fixed value](https://github.com/ladybug-analysis-tools/ladybug-web/compare/gh-pages...mostaphaRoudsari:gh-pages#diff-1d7ddbf1f294c5ce2dfc468bcad801fcR194) but as you mentioned before we can get it from google or calculate it based on longitude. I compared the results of the SunCalc to NOAA algorithm and it's acceptable but not very accurate.

I also had to [modify](https://github.com/ladybug-analysis-tools/ladybug-web/compare/gh-pages...mostaphaRoudsari:gh-pages#diff-1d7ddbf1f294c5ce2dfc468bcad801fcR412) `converPosition` function.

[Here](http://mostapharoudsari.github.io/ladybug-web/analemma-3d/analemma-3d-r4.html) is the live version of the code after the changes.

### CODE REVIEW

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Looks good. Brilliant sleuthing!

**Comment by theo-armour** [comment]
Can you see me jumping up and down with excitement!

This is now a team effort. Yay!

I've been working on UTC and timezone offsets - so should be able to wrap up that part of the issues.

Thank you so much @mostaphaRoudsari. I might have got there in the end but your help not only made things happen fast - but also demonstrate we can work together.

**Comment by mostaphaRoudsari** [comment]
Thanks @theo-armour! We definitely can. Your code is very clean and easy to follow.

This will have more users than any other ladybug and honeybee tools that we have in the plugins. Very excited to share it with more people soon.

**Comment by theo-armour** [comment]
> > Your code is very clean and easy to follow.

Thank you!

I try and follow [MDCS](https://github.com/mrdoob/three.js/wiki/Mr.doob's-Code-Style%E2%84%A2)

And even more importantly - to keep the Three.js mission statement in mind:

> > JavaScript 3D library: The aim of the project is to create a lightweight 3D library with a very low level of complexity — in other words, for dummies. 

I will be add something about this coding style in the repo before too long.

The goal is to help engineers learn to build simple things in code - so they don't have to ask programmers to do it for them.

**Pull request merged**
